const titles = {
    1995: [
        // 'Garbage Only Happy When It Rains',
        'Jewel You Were Meant For Me',
        'Michael Jackson Scream',
    ],

    1996: [
        'Garbage Stupid Girl',
        'Jamiroquai Virtual Insanity',
        'Metallica Until It Sleeps',
        'Savage Garden I Want You',
        // 'Sheryl Crow If It Makes You Happy',
        'Smashing Pumpkings 1979',
    ],

    1997: [
        // 'Backstreet Boys As Long As You Love Me',
        'Chumbawamba Tubthumping',
        'Daft Punk Around The World',
        'Eagle Eye Cherry Save Tonight',
        'Fiona Apple Criminal',
        'Foo Fighters Everlong',
        'Foo Fighters Monkey Wrench',
        'Goo Goo Dolls Iris',
        // 'Meredith Brooks Bitch',
        'Natalie Imbruglia Torn',
        'NSYNC Tearing Up My Heart',
        'Third Blind Eye SemiCharmed Life',
        'Tonic If You Could Only See',
        'The Verve Bitter Sweet Symphony',
        'The Verve Bitter Lucky Man',
        'The Wallflowers One Headlight',
    ],

    1998: [
        'Aerosmith I Dont Want To Miss A Thing',
        'Alanis Morissette Thank You',
        'Bryan Adams When Youre Gone',
        'El Gran Silencio Duerme Sonando',
        // 'Fey Diselo Con Flores',
        'Garbage I Think Im Paranoid',
        'Hanson Weird',
        'Lauryn Hill Doo Wop',
        'Madonna Frozen',
        'Placebo Pure Morning',
        // 'Robbie Williams Millenium',
        'SemiSonic Closing Time',
        'Shawn Mullins Lullaby',
        // 'Stardust Music Sounds Better With You',
        'The Cardigans Favourite Game',
        // 'The Corrs So Young',

        'Backstreet Boys All I Have To Give',
        'Britney Spears Baby One More Time',
        'Lenny Kravitz Fly Away',
        'Robbie Williams Angels',
    ],

    1999: [
        'Ana Torroja Ya No Te Quiero',
        'ATeens Gimme Gimme Gimme',
        'ATeens Super Trouper',
        'Blink 182 Whats My Age Again',
        'Blur Coffee And TV',
        'Britney Spears Born To Make You Happy',
        'Britney Spears Crazy',
        'Britney Spears From The Bottom Of My Broken Heart',
        'Café Quijano La Lola',
        'Celine Dion Thats The Way It Is',
        // 'Cher All Or Nothing',
        'Creed Higher',
        // 'Ely Guerra Tengo Frio',
        'Eminem My Name Is',
        // 'Fey Canela',
        'Destinys Child Say My Name',
        'Fiona Apple Fast As You Can',
        'Five If Ya Gettin Down',
        'Five Keen On Movin',
        'Geri Halliwell Look At Me',
        'Geri Halliwell Mi Chico Latino',
        'Gustavo Cerati Puente',
        'Illya Kuryaki And The Valderramas Jennifer Del Estero',
        'Jennifer Lopez Waiting For Tonight',
        'Lene Marlin Sitting Down Here',
        'Live Dolphins Cry',
        'Lynda No Quiero Verte',
        'M2M Dont Say You Love Me',
        // 'Madison Avenue Dont Call Me Baby',
        'Marc Anthony I Need To Know',
        'Mariah Carey Heartbreaker',
        'Marilyn Manson Coma White',
        // 'Metallica No Leaf Clover',
        'New Radicals Someday Well Know',
        'No Doubt New',
        // 'Noelia Tu',
        'Orgy Blue Monday',
        // 'Robbie Williams Shes The One',
        'Rage Against The Machine Guerrilla Radio',
        'Santana Maria Maria',
        'Shakira No Creo',
        'Shakira Ojos Asi',
        'Sheryl Crow Anything But Down',
        'Shania Twain Man I Feel Like A Woman',
        'Sixpence None The Richer There She Goes',
        'Smash Mouth All Star',
        'Sugar Ray Someday',
        'TLC Unpretty',
        'Tal Bachman Shes So High',
        'Tam Tam Go Atrapados En La Red',
        'The Chemical Brothers Let Forever Be',
        'The Offspring Pretty Fly',
        'The Offspring Shes Got Issues',
        'The Offspring The Kids Arent Alright',
        'Tom Jones Burning Down The House',
        'Vanessa Amorosi Absolutely Everybody',
        // 'Vertigogo Ese Oscuro Objeto Del Deseo',
        // 'Westlife Flying Without Wings',
        // 'Westlife I Have A Dream',
        // 'Whigfield Be My Baby',
        'Zurdok Si Me Adverti',
    ],

    2000: [
        'La Mosca TseTse Para No Verte Mas',
        '98 Give Me Just One Night',
        'ATeens Dancing Queen',
        'ATeens Upside Down',
        'Aaron Carter Aarons Party',
        'All Saints Black Coffee',
        'Baha Men Who Let The Dogs Out',
        'Backstreet Boys The One',
        'BON Boys',
        'BON Nobody',
        'Bon Jovi Say It Isnt So',
        'Coldplay Yellow',
        'Craig David Walking Away',
        'Destinys Child Independent Women Part I',
        'Eminem The Way I Am',
        'Five Dont Want To Let You Go',
        'Foo Fighters Break Out',
        // 'Fuel Hemorrhage (HD)',
        'Incubus Drive',
        'Korn Somebody Someone',
        'Lara Fabian I Will Love Again',
        // 'LeAnn Rimes Cant Fight The Moonlight',
        'Lynda Corazon Perdido',
        'Lynda A Mil Por Hora',
        'Jennifer Lopez Lets Get Loud',
        'Jessica Simpson I Think Im In Love With You',
        'Juanes Fijate',
        'Juanes Nada',
        'Juanes Podemos Hacernos Daño',
        'Laura Pausini Entre Tu Y Mil Mares',
        'M2M Everything You Do',
        'Marilyn Manson Disposable Teens',
        'MDO Te Quise Olvidar',
        'Matchbox Twenty If Youre Gone',
        'Melanie C Never Be The Same Again',
        'Metallica I Disappear',
        // 'Mest Whats The Dillio',
        'Moby Southside',
        'Nine Days Absolutely Story Of A Girl',
        'No Doubt Bathwater',
        // 'Noelia Tú',
        'NSYNC This I Promise You',
        'Oasis Sunday Morning Call',
        'Outkast Ms Jackson',
        // 'OV7 Enloqueceme',
        // 'OV7 Más Que Amor',
        'OV7 Shabadaba',
        'Papa Roach Last Resort',
        'Red Hot Chilli Peppers Californication',
        'Red Hot Chilli Peppers Otherside',
        'Robbie Williams Kids',
        'S Club 7 Bring It All Back',
        'S Club 7 Natural',
        'S Club 7 S Club Party',
        'Sade By Your Side',
        'Santana Corazón Espinado',
        'Sisqo Thong Song',
        'Spiller Groovejet',
        'Sting Desert Rose',
        'Tarkan Hepsi Senin Mi',
        'Texas In Demand',
        // 'Toploader Dancing In The Moonlight',
        'Wheatus Teenage Dirtbag',
    ],

    2001: [
        'Aerosmith - Fly Away From Here',
        'Alejandra Guzman De Verdad',
        'ATeens Halfway Around The World',
        'Alicia Keys Fallin',
        'Alien Ant Farm Smooth Criminal',
        'Blue All Rise',
        'Bon Jovi Thank you For Loving Me',
        'Britney Spears Dont Let Me Be The Last To Know',
        'Christina Milian AM to PM',
        'Coldplay Trouble',
        'Destinys Child Emotion',
        // 'Dave Matthews Band I Did It',
        'Eve Let Me Blow Your Mind',
        // 'Eve Whos That Girl?',
        'Incubus Wish You Were Here',
        'Janet Jackson Someone To Call My Lover',
        'Jennifer Lopez Im Real',
        'Jimmy Eat World The Middle',
        'Kabah Te Necesito',
        'La Oreja De Van Gogh La Playa',
        'Laura Pausini Un Error De Los Grandes',
        'Lifehouse Hanging By A Moment',
        'Linkin Park One Step Closer',
        'Limp Bizkit My Way',
        'Mandy Moore In My Pocket',
        'Maria Bestar Pensando En Ti',
        // 'Marilyn Manson The Fight Song',
        'Mary J Blige Family Affair',
        'Michelle Branch Everywhere',
        'Mick Jagger God Gave Me Everything I Want',
        'Modjo What I Mean',
        'Nelly Ride Wit Me',
        'Nelly Furtado Im Like A Bird',
        'Nickelback How You Remind Me',
        'Papa Roach Between Angels And Insects',
        'Paulina Rubio Tal Vez Quizas',
        'Paulina Rubio Yo No Soy Esa Mujer',
        'POD Alive',
        'Puddle Of Mudd Blurry',
        'Ricky Martin Loaded',
        'S Club 7 Dont Stop Movin',
        'Shaggy Angel',
        // 'Shaggy Dance And Shout',
        'Shaggy It Wasnt Me',
        'Shaggy Luv Me Luv Me',
        'Staind Its Been Awhile',
        'Stone Temple Pilots Days Of The Week',
        // 'Strokes Last Night',
        // 'Sugar Ray When Its Over','
        'Sum 41 Fat Lip',
        'Sum 41 In Too Deep',
        'The Offspring Defy You',
        'The Offspring Want You Bad',
        'Train Drops Of Jupiter',
        'Travis Side',
        // 'Usher You Remind Me',
        'Weezer Hash Pipe',
        'Westlife Queen Of My Heart',
    ],

    2002: [
        'Aleks Syntek Bendito Tu Corazon',
        'Atomic Kitten Be With You',
        'Box Car Racer There Is',
        'Coldplay The Scientist',
        'Darren Hayes Strange Relationship',
        'David Bisbal Dígale',
        'DB Boulevard Point Of View',
        'Faithless One Step Too Far',
        'Filter Where Do We Go From Here',
        'Incubus Are You In?',
        'Incubus Nice To Know You',
        'Incubus Wish You Were Here',
        'Jennifer Lopez Aint It Funny',
        'John Mayer Your Body Is A Wonderland',
        'Kylie Minogue Love At First Sight',
        'La Ley Intenta Amar',
        'La Oreja De Van Gogh La Playa',
        'Las Ketchup Asereje',
        'Linkin Park Points Of Authority',
        'Michelle Branch All I Wanted',
        'Natalia Lafourcade Busca Un Problema',
        'Natalie Imbruglia Wrong Impression',
        'Nelly Hot In Herre',
        'New Found Glory My Friends Over You',
        'Oasis Little By Little',
        'Papa Roach She Loves Me Not',
        'Paul Oakenfold Starry Eyed Surprise',
        'Pink Family Portrait',
        'Red Hot Chilli Peppers The Zephyr Song',
        'Queens of The Stone Age No One Knows',
        'Ruff Endz Someone To Love You',
        'Sheryl Crow Soak Up The Sun',
        'Sophie Ellis Bextor Music Gets The Best Of Me',
        'System Of A Down Chop Suey',
        'Thalia No Me Enseñaste',
        'Vanessa Carlton A Thousand Miles',
        'The Vines Get Free',
    ],
    // 83 ENTRIES
    2003: [ // CHECK BILLBOARD HOT 100 AND AUSTRALIA TOP 100
        '3 Doors Down Here Without You',
        '50 Cent In Da Club',
        // '50 Cent 21 Questions',
        // '50 Pimp',
        // 'AFI The Leaving Song',
        'AFI Girls Not Grey',
        'Aleks Syntek Duele El Amor',
        'Aleks Syntek Te Sone',
        'Alejandro Sanz No Es Lo Mismo',
        'Alejandro Sanz Regalame La Silla Donde Te Espere',
        'Alicia Keys You Dont Know My Name',
        'Alizee Jen Ai Marre',
        'Amiel Love Song',
        'Audioslave Show Me How To Live',
        'Audioslave Like A Stone',
        // 'ATeens A Perfect Match',
        'Avril Lavigne Im With You',
        'Avril Lavigne Losing Grip',
        // 'Baby Bash Suga Suga',
        'Belanova Tus Ojos',
        // 'Belanova Aun Asi Te Vas',
        // 'Belinda Esa Boba Nina Nice',
        // 'Belinda Lo Siento',
        'Beyonce Baby Boy',
        'Beyonce Crazy In Love',
        'Black Eyed Peas Shut Up',
        'Black Eyed Peas Where Is The Love',
        'Blink 182 Feeling This',
        // 'Blue Sorry Seems To Be The Hardest Word',  // +++++
        // 'Blur Crazy Beat',
        'Bon Jovi All About Lovin You',
        'Britney Spears Me Against The Music',
        // 'Cafe Tacuba Cero Y Uno',
        // 'Cafe Tacuba EO El Sonidero', // +++++
        'Celine Dion I Drove All Night',
        // 'Cartel De Santa Todas Mueren Por Mi',
        'Christina Aguilera Beautiful',
        'Christina Aguilera Cant Hold Us Down',
        'Christina Aguilera Fighter',
        'Christina Aguilera The Voice Within',
        'Coldplay Clocks',
        'Coldplay God Put A Smile Upon Your Face',
        // 'Control Machete Bien Bien',
        'Counting Crows Big Yellow Taxi',
        // 'Crazy Town Hurt You So Bad',
        'Deftones Minerva',
        'Dido Life For Rent',
        'Dido White Flag',
        // 'Elan Midnight',
        'Eminem Sing For The Moment',
        'Evanescence Bring Me To Life',
        'Evanescence Going Under',
        'Evanescence My Immortal',
        'Foo Fighters Times Like These',
        'Fountains Of Wayne Stacys Mum',
        // 'Genitallica Prendelo',
        'Good Charlotte Boys And Girls',
        'Good Charlotte Lifestyle Of The Rich And The Famous', // MAY 2003, 1 APPEARANCE, 8
        // 'Gustavo Cerati Cosas Imposibles',
        // 'Gustavo Cerati Cosas Karaoke',
        // 'Interpol Obstacle 1',
        // 'Interpol Slow Hands',
        // 'Jamelia Superstar',
        'Jennifer Lopez All I Have',
        // 'Jennifer Im Glad',
        'Jet Are You Gonna Be My Girl',
        'Jewel Intuition',
        'Jewel Stand',
        'John Mayer Bigger Than My Body',
        'Juanes Fotografia',
        'Juanes Mala Gente',
        'Julieta Venegas Andar Conmigo',
        // 'Jumbo Bajo Control',
        'Justin Timberlake Cry Me A River',
        'Justin Timberlake Rock Your Body',
        'Justin Timberlake Senorita',
        'Kelly Rowland Stole',
        // 'Kabah Por Ti',
        // 'Kashmir Surfing The Warm Industry',
        // 'Kelly Osborne Come Dig Me Out',
        // 'Kinky Presidente',
        // 'Korn Did My Time',
        'Kylie Minogue Slow',
        // 'La Ley Amate Y Salvate',
        'La Ley Mas Alla',
        'La Oreja De Van Gogh Puedes Contar Conmigo',
        'La Oreja De Van Gogh Rosas',
        'Linkin Park Faint',
        'Linkin Park Numb',
        'Linkin Park Somewhere I Belong',
        'Limp Bizkit Behind Blue Eyes',
        'Limp Bizkit Eat You Alive',
        // 'Madonna American Life',
        'Madonna Hollywood',
        'Matchbox 20 Unwell',
        'Mana Mariposa Traicionera',
        // 'Mariah Carey Boy I Know What You Want',
        // 'Mariah Carey Boy I Need You',
        'Marilyn Manson Mobscene',
        // 'Marilyn Manson This Is The New Shit',
        'Melanie C Here It Comes',
        'Metallica Frantic',
        // 'Metallica St Anger',
        'Michelle Branch Are You Happy Now',
        'Missy Elliot Gossip Folks',
        'Moenia En Que Momento',
        'Molotov Frijolero',
        // 'Molotov Here We Kum',
        // 'Molotov Hit Me',
        // 'Natalia Lafourcade Te Quiero Dar',
        // 'Nelly Work It',
        'Nick Carter I Got You',
        'Nickelback Someday',
        'No Doubt Its My Life',
        // 'Otown These Are The Days',
        'Outkast Hey Ya',
        // 'Panda Ya No Jalaba',
        'Paulina Rubio Baila Casanova',
        'Placebo Special Needs',
        'Placebo The Bitter End',
        'Plastilina Mosh Peligroso Pop',
        // 'Pink Family Portrait',
        // 'Pink Feel Good Time',
        'Pink God Is A DJ',
        // 'Pink Trouble',
        // 'POD Sleeping Awake',
        // 'POD Will You',
        'QBO Desvanecer',
        // 'QBO No Mas',
        // 'Queens Of The Stone Age Go With The Flow',
        // 'Radiohead Go To Sleep',
        // 'Radiohead There There',
        'R Kelly Ignition',
        'Red Hot Chilli Peppers Cant Stop',
        'Red Hot Chilli Peppers Fortune Faded',
        'Red Hot Chilli Peppers Universally Speaking',
        // 'Ricky Martin Jaleo',
        'Ricky Martin Tal Vez',
        // 'Robbie Williams Come Undone',
        // 'Robbie Williams Something Beautiful',
        'Sean Paul Get Busy',
        // 'Shaggy Hey Sexy Lady',
        'Simple Plan Addicted',
        'Simple Plan Id Do Anything',
        'Simple Plan Perfect',
        'Stacie Orrico More To Life',
        'Stacie Orrico Stuck',
        'Starsailor Silence Is Easy',
        'Sum 41 Still Waiting',
        // 'Sum 41 The Hell Song',
        // 'Sum 41 Over My Head',
        // 'System Of A Down Boom',
        // 'Thalia A Quien Le Importa',
        // 'Thalia Baby Im In Love',
        // 'Thalia I Want You',
        'The Ataris Boys Of Summer',
        'The Ataris The Saddest Song',
        // 'The Calling For You',
        'The Darkness I Believe In A Thing Called Love',
        // 'The Mars Volta Inertiatic ESP',
        // 'The Music Getaway',
        // 'The Sounds Living In America',
        // 'The Strokes 1251',
        // 'The Vines Outtathaway',
        'The White Stripes Seven Nation Army',
        // 'The White Stripes The Hardest Button To Button',
        'Tiziano Ferro Tardes Negras',
        // 'Travis Reoffender',
        // 'U2 Vertigo',
        // 'Yeah Yeah Yeahs Pin',
        'Yeah Yeah Yeahs Maps',
        // 'Zoe Peace And Love',
    ],
    // 104 entries
    // 10 MAS PEDIDOS - DONE
    // 100 MAS PEDIDOS - DONE
    // TOP 20 - DONE
    2004: [
        'AFI Silver And Cold',
        'Alanis Morissette Everything',
        'Alex Ubago Aunque No Te Pueda Ver',
        // 'Alex Ubago Cuanto Antes',
        'Alex Ubago Dame Tu Aire',
        'Ashlee Simpson Pieces Of Me',
        'ATeens I Promised Myself',
        'Avril Lavigne Dont Tell Me',
        'Avril Lavigne My Happy Ending',
        'Avril Lavigne Nobodys Home',
        'Belinda Angel',
        // 'Belinda Be Free',
        'Belinda Vivir',
        'Beyonce Naughty Girl',
        'Black Eyed Peas Hey Mama',
        'Black Eyed Peas Lets Get It Started',
        'Blink 182 Always',
        'Blink 182 I Miss You',
        // 'Blink 182 Down',
        'Britney Spears Everytime',
        'Britney Spears My Prerrogative',
        'Britney Spears Toxic',
        'Cafe Tacuba Eres',
        // 'Cartel De Santa Blah Blah Blah',
        'Cartel De Santa La Pelotona',
        'Ciara 12 Step',
        // 'Chingy Holidae Inn',
        // 'Christina Aguilera Car Wash',
        'D12 My Band',
        'Destinys Child Lose My Breath',
        // 'Dido Dont Leave Home',
        'Eminem Just Lose It',
        'Eric Prydz Call On Me',
        'Evanescence Everybodys Fool',
        'Fey La Fuerza Del Destino',
        'Fobia Hoy Tengo Miedo',
        'Franz Ferdinand Take Me Out',
        // 'Good Charlotte Hold On',
        'Good Charlotte Predictable',
        'Green Day American Idiot',
        'Green Day Boulevard Of Broken Dreams',
        'Gwen Stefani What You Waiting For',
        'Hanson Penny And I',
        'Hilary Duff Come Clean',
        'Hilary Duff Fly',
        // 'Hilary Duff Our Lips Are Sealed',
        'Hilary Duff So Yesterday',
        'Hoobastank Same Direction',
        'Hoobastank The Reason',
        'Incubus Megalomaniac',
        'Incubus Talk Shows On Mute',
        // 'Jayz Numb Encore',
        // JC Chasez "All Day Long I Dream About Sex",
        'JD Natasha Lagrimas',
        'Jesse McCartney Beautiful Soul',
        'Jojo Leave Get Out',
        'Joss Stone Super Duper Love',
        'Joss Stone You Had Me',
        'Juanes Nada Valgo Sin Tu Amor',
        'Juanes Volverte A Ver',
        'Julieta Venegas Algo Esta Cambiando',
        'Julieta Venegas Lento',
        // 'Justin Timberlake Im Loving It',
        // 'Kalimba No Me Quiero Enamorar',
        'Keane Everybodys Changing',
        'Keane Somewhere Only We Know',
        'Kelis Milkshake',
        'Kelis Trick Me',
        'Kelly Clarkson Breakaway',
        'Kelly Clarkson Since You Been Gone',
        // 'Korn Yall Want A Single',
        // 'Kylie Minogue Chocolate',
        'Kylie Minogue Red Blooded Woman',
        'Linkin Park Breaking The Habit',
        'Lu Por Besarte',
        'Lu Una Confusion',
        'Maria Barracuda Chale',
        'Maria Mena Youre The Only One',
        'Marilyn Manson Personal Jesus',
        'Maroon 5 This Love',
        'Maroon 5 She Will Be Loved',
        'Mew Am I Wry',
        'Miranda Yo Te Dire',
        'Moenia Ni Tu Ni Nadie',
        'Modest Mouse Float On',
        'Natasha Bedingfield These Words',
        // 'Nelly Furtado Forca',
        'Nelly Furtado Powerless',
        'Nelly Furtado Try',
        'Nelly Furtado Explode',
        'Nerd She Wants To Move',
        'Nina Sky Move Ya Body',
        // 'Outkast The Way You Move',
        'Outkast Roses',
        'Papa Roach Getting Away With Murder',
        // 'Paulina Rubio Algo Tienes',
        // 'Paulina Rubio Dame Otro Tequila',
        // 'Rammstein Mein Teil',
        // 'Robbie Williams Radio',
        'Ryan Cabrera True',
        'Sean Paul Im Still In Love With You',
        'Seether Broken',
        // 'Shakira Poem To A Horse',
        // 'Simple Plan Dont Want To Think About You',
        'Simple Plan Welcome To My Life',
        'Stacie Orrice I Promise',
        'The Chemical Brothers Galvanize',
        'The Killers Mr Brightside',
        'The Killers Somebody Told Me', // CONTINUE UPWARDS TO CHECK IF WE HAVE YOU ON THE LIST
        'The Rasmus In The Shadows',
        'The Rasmus Guilty',
        'The Scissor Sisters Laura',
        'The Scissor Sisters Take Your Mama',
        'The Strokes Reptilia',
        'The Vines Ride',
        'Usher Confessions Part II',
        'Usher My Boo',
        'Usher Yeah',
        'Velvet Revolver Fall To Pieces',
        'Westlife Mandy',
        'Yellowcard Ocean Avenue',
        'Yellowcard Only One',
        'Zoe Love',
    ]
}


// 3 Doors Down - When I'm Gone (HD)
// Basement Jaxx - Where's Your Head At?
// Kabah - Casi Al Final
// Kinky - Ejercicio 16/
// Sin Bandera - Kilómetros
// Sum 41 - Motivation
// The Calling - Adrienne
// Weezer - Deep Nose